### ISSUE TITLE
Translation on github

### ISSUE THREAD

**Issue by HakaCode** [DIO-David1327/DIO-TOOLS-David1327#1]
would there be any chance to contribute translations to the project within github itself?

**Comment by DIO-David1327** [comment]
at the moment i'm new to github suddenly I don't know how to do it but it's a project

I would like to separate the translation is my script 
to make the translation easier and reduce the size of my script
but i still don't understand everything about github

**Comment by HakaCode** [comment]
> at the moment i'm new to github suddenly I don't know how to do it but it's a project
> 
> I would like to separate the translation is my script to make the translation easier and reduce the size of my script but i still don't understand everything about github

:brazil: Tranquilo também sou relativamente novo por aqui, mas podemos aprender juntos caso queira.
:us: Okay, I'm relatively new here too, but we can learn together if you want.

**Comment by DIO-David1327** [comment]
Thank you it's nice now I don't have time But I am in a hurry to resume development 😀
