### ISSUE TITLE
Translate conquest menu  military siege / armor level troops in city 

### ISSUE THREAD

**Issue by Yann-Eveno** [DIO-David1327/DIO-TOOLS-David1327#6]
![vpkZ0pxvt3](https://user-images.githubusercontent.com/36241584/182687770-ba1fba1f-8c62-4373-bfbf-896150a1cef3.jpg)

**Comment by DIO-David1327** [comment]
Bonjour, ce sera résolu dans la prochaine mise à jour.
Merci de l'avoir signalé :)

Vous avez la possibilité d'attendre la prochaine mise à jour complète ou de tester la nouvelle traduction (version bêta).
Test: https://github.com/DIO-David1327/DIO-TOOLS-David1327/raw/6-translate-conquest-menu-military-siege-armor-level-troops-in-city/code.user.js
